build:
  nodes:
    builder:
      environment:
        java: java-8-oracle
      dependencies:
        before:
          - command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
            idle_timeout: 600