build:
  nodes:
    builder:
      resources:
        cpus: 8
      environment:
        java: java-8-oracle
        variables:
          _JAVA_OPTIONS: '-Xms512m -Xmx6144m'
      commands:
        - command: mvn install -DskipTests=true -B -V
          idle_timeout: 300